name: Fetch and Update Lake Data

on:
  schedule:
    - cron: "27 * * * *"  # Runs at the 27th minute of every hour
  workflow_dispatch:  # Allows manual execution

jobs:
  fetch_lake_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Create necessary directories
        run: mkdir -p logs data

      - name: Run lake data fetch script
        run: python .github/scripts/fetch_lake_data.py

      - name: Commit and Push CSV Updates
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/*.csv
          git commit -m "📊 Updated lake data (automated)" || echo "No changes to commit"
          git push
