name: Fetch and Update Lake Data

on:
  schedule:
    - cron: "27 * * * *"  # Runs every hour at the 27th minute
  workflow_dispatch:  # Allows manual execution

permissions:
  contents: write  # Ensures the GitHub Action can push changes

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full commit history is fetched

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run Python Script to Fetch Data
        run: python .github/scripts/fetch_lake_data.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch Latest Changes from Remote
        run: |
          git fetch origin main
          git reset --hard origin/main  # Ensure local branch matches remote
          git pull origin main --rebase  # Merge latest changes

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git commit -m "Updated lake data" || echo "No changes to commit"
          git push origin main
