name: Fetch Lake Data

on:
  schedule:
    - cron: "30 * * * *"  # Runs every hour at minute 30
  workflow_dispatch:

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensure GitHub Actions has permission to write changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run data fetch script
        run: python .github/scripts/fetch_lake_data.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git commit -m "Updated lake data" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/jnkilgo/Chain-of-Lakes-Monitoring.git main
