name: Fetch and Update Lake Data

on:
  schedule:
    - cron: "27 * * * *"  # Runs at the 27th minute of every hour
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  fetch_lake_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # We'll use our own token
          fetch-depth: 0  # Ensures full history is available for conflict resolution

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install requests beautifulsoup4

      - name: Pull Latest Changes to Avoid Conflicts
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git fetch origin main
          git reset --hard origin/main  # Forcefully synchronize with the remote

      - name: Run Python Script
        run: python .github/scripts/fetch_lake_data.py

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Updated lake data" || echo "No changes to commit"
          # Retry pushing to handle race conditions
          for i in {1..3}; do
            git fetch origin main
            git rebase origin/main  # Rebase local changes on top of the latest remote changes
            if git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/jnkilgo/Chain-of-Lakes-Monitoring.git main; then
              echo "Push succeeded"
              break
            else
              echo "Push failed, retrying ($i/3)..."
              sleep 5
            fi
          done
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
