name: Fetch and Update Lake Data

on:
  schedule:
    - cron: "27 * * * *"  # Runs at the 27th minute of every hour
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  fetch_lake_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Using personal access token instead
          fetch-depth: 0  # Fetch full history to avoid issues

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install requests beautifulsoup4

      - name: Force Sync Repository with Remote
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git fetch origin main
          git reset --hard origin/main  # Resets local branch to match remote exactly

      - name: Run Python Script
        run: python .github/scripts/fetch_lake_data.py

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Updated lake data" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/jnkilgo/Chain-of-Lakes-Monitoring.git main --force
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
