name: Fetch and Update Lake Data

on:
  schedule:
    - cron: "27 * * * *"  # Runs at the 27th minute of every hour
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  fetch_lake_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Ensures we use our token for authentication
          fetch-depth: 0  # Ensures full history is available for proper commits

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install requests beautifulsoup4

      - name: Pull Latest Changes to Avoid Conflicts
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git fetch origin main
          git reset --hard origin/main  # Ensures we have the latest repository state

      - name: Run Python Script
        run: python .github/scripts/fetch_lake_data.py

      - name: Commit and Push Changes
        run: |
          git add data/*.csv  # Track only CSV files inside the correct data folder
          git commit -m "🔄 Updated lake data (Auto)" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/jnkilgo/Chain-of-Lakes-Monitoring.git main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
