name: Fetch and Update Lake Data

on:
  schedule:
    - cron: "27 * * * *"  # Runs at the 27th minute of every hour
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  fetch_lake_data:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub-provided token
          fetch-depth: 0  # Ensures full history is available

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: pip install requests beautifulsoup4

      # Step 4: Run Python Script
      - name: Run Python Script
        run: python .github/scripts/fetch_lake_data.py

      # Step 5: Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Updated lake data" || echo "No changes to commit"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/jnkilgo/Chain-of-Lakes-Monitoring.git
          git push origin main
