name: Fetch Lake Data

on:
  schedule:
    - cron: "27 * * * *" # Runs at the 27th minute of every hour
  workflow_dispatch: # Allows manual execution

jobs:
  fetch_lake_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r .github/scripts/requirements.txt

      - name: Run fetch_lake_data.py script
        run: python .github/scripts/fetch_lake_data.py

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/jnkilgo/Chain-of-Lakes-Monitoring.git
          git add .
          git commit -m "Updated lake data"
          git push origin main
