name: Run SSL Debug Script

on:
  workflow_dispatch:  # Allows manual triggering from the Actions tab

jobs:
  ssl_debug:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Python Environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install Dependencies
      - name: Install Required Python Libraries
        run: pip install requests

      # Step 4: Run the SSL Debug Script
      - name: Run SSL Debug Script
        run: python .github/scripts/fetch_lake_data_debug.py
