name: Test Push with GITHUB_TOKEN

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Use GITHUB_TOKEN for authentication
          fetch-depth: 0  # Ensures full history is available

      - name: Set up Git Identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Create a Test Commit
        run: |
          echo "Test commit" >> test.txt
          git add test.txt
          git commit -m "Test commit using GITHUB_TOKEN" || echo "No changes to commit"

      - name: Push Changes
        run: |
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/jnkilgo/Chain-of-Lakes-Monitoring.git main
