name: SSL Debug Test

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  ssl_debug_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install requests

      - name: Run SSL Debug Script
        run: python ".github/scripts/SSL_Debug"
